#デフォルトで用意されているmake!タスクをすべて無効化
[config]
skip_core_tasks = true

#C言語はこれがベストっぽい
[tasks.COMPILE]
description = "compile source files"
script = ['''
#!/bin/bash
gcc main.c -o hello
./hello
''']

#C言語のコンパイルだけは以下でできる
[tasks.c]
description = "exec c program"
script_runner = "gcc"
script_extension = "c"
script = '''
#include <stdio.h>

int main(void) {
  printf("Hello, cargo-make!\n");
  return 0;
}
'''

[tasks.rust]
description = "exec rust program"
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! ```
fn main() {
  const HELLO: &str = "Hello, cargo-make!";
  println!("{}", HELLO);
}
'''

[tasks.python]
description = "exec python program"
script_runner = "python3"
script_extension = "py"
script = '''
print("Hello, cargo-make!")
'''

[tasks.js]
description = "exec js progrm"
script_runner = "node"
script_extension = "js"
script = '''
console.log("Hello, cargo-make!")
'''

[tasks.ts]
description = "exec ts program"
script_runner = "bun"
script_extension = "ts"
script = '''
const hello: string = "Hello, cargo-make!";
console.log(hello);
'''

[tasks.r]
description = "exec r program"
script_runner = "Rscript"
script_extension = "r"
script = '''
paste0("Hello, cargo-make!")
'''
